FROM node:10-slim

LABEL "com.github.actions.name"="Verdaccio Webpack E2E"
LABEL "com.github.actions.description"="test webpack app"
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="#4b5e40"

# Copy the action's code into the container
COPY . example/
RUN pwd
